default: &default
  wit:
    frontend: <%= ENV['WIT_FRONTEND_TOKEN'] %>
    backend: <%= ENV['WIT_BACKEND_TOKEN'] %>
  map:
    key: <%= ENV['GOOGLE_MAP_KEY'] %>
  tags:
    - rice
    - noodle
    - chinese
    - japanese

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
